---
- name: Copiar archivo localmente
  hosts: localhost
  tasks:
    - name: Copiar archivo
      copy:
        src: /home/ubuntu/Practica1SA/dist
        dest: /var/www/
    - name: Copiar nginx file
      copy:
        src: /home/ubuntu/Practica1SA/nginx
        dest: /etc/nginx/sites-enabled/
