---
- name: install nginx server and static website
  hosts: all
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: deploy webpage
      copy:
        src: /home/ubuntu/Practica1SA2/pagina/front.html
        dest: /var/www
